version: '3.8'
services:
  frontend:
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    networks:
      - app-network

  backend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build: ./db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge